### ISSUE TITLE
Wrong order

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-combine-solidity#1]
```
myc:32:24: TypeError: Definition of base has to precede definition of derived contract
contract BasicToken is ERC20Basic {
                       ^--------^
```
when I tried to combine some token contract it didn't give me the correct order.

**Comment by igorbarinov** [comment]
@rstormsf please provide more details

**Comment by rstormsf** [comment]
@igorbarinov 
I will post the contract that I used as soon as the client goes to public ICO.

**Comment by igorbarinov** [comment]
@rstormsf can you try on open zeppelin contract and check if you can replicate the error

**Comment by igorbarinov** [comment]
@rstormsf thank you; I confirmed the bug.
@vbaranov, please take a look. There is a wrong order of imports in generated file. We need to follow the order.

**Comment by rstormsf** [comment]
@vbaranov nice work! I verified it in this video: https://youtu.be/ShW2zQcY4LY

**Comment by vbaranov** [comment]
@haggins could you specify what project are you trying to flatten? Where can I reproduce the issue?

**Comment by haggins** [comment]
@vbaranov I've setup a minimal working repository with the same directory structure: https://github.com/haggins/flattener-bug-demo

**Comment by vbaranov** [comment]
@haggins I've refactored the code of flattener https://github.com/poanetwork/solidity-flattener/pull/27. The order of contracts should be correct now. Could you please pull updates and let me know?

**Comment by haggins** [comment]
@vbaranov Wow, that was really a massive refactoring! You know what? It worked! :1st_place_medal: 
Thanks for your dedication.
