### ISSUE TITLE
Weird behavior double contracts

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-combine-solidity#17]
Steps:

https://github.com/rstormsf/oracles-presale/tree/removeWhitelist - git clone this branch
run `npm start contracts/PresaleOracles.sol`

get generated file:
https://gist.github.com/rstormsf/d5f14b4280fe956f95df66582d78a461

Notice a few issues:
1. Double BasicToken
2. Double Safemath
3. Double PresaleOracles

Critical:
I don't understand where BasicToken comes from with `safeSub` code. 
Example:
https://gist.github.com/rstormsf/d5f14b4280fe956f95df66582d78a461#file-presaleoracles_flat-sol-L197

It should only have this BasicToken contract:
https://gist.github.com/rstormsf/d5f14b4280fe956f95df66582d78a461#file-presaleoracles_flat-sol-L90

Everything below line 187 should be removed:
https://gist.github.com/rstormsf/d5f14b4280fe956f95df66582d78a461#file-presaleoracles_flat-sol-L187

Another question: Where does it get wrong BasicToken with old usage of old SafeMath lib?

**Comment by igorbarinov** [comment]
@vbaranov please take a look

**Comment by vbaranov** [comment]
There are two `zeppelin-solidity` of different versions in your dependencies in package.json: 
- directly from `"zeppelin-solidity": "^1.3.0"` 
- and from `"solidity-coverage": "^0.4.0"`

Need more R&D to avoid this types of bugs and choose correct contract from dependency

**Comment by igorbarinov** [comment]
@vbaranov why do we look into package.json?
the flattener should only flat `sol` files and their imports/dependencies inherited from solidity files.  Why flattener look into packages.json file? @vbaranov

**Comment by vbaranov** [comment]
Script doesn't look into package.json. It looks for `BasicToken.sol` and found it in `./node_modules/zeppelin-solidity/contracts/token` and in `./node_modules/solidity-coverage/test/contracts/token`.

**Comment by vbaranov** [comment]
@rstormsf solution for your issue in [refactor](https://github.com/oraclesorg/oracles-combine-solidity/tree/refactor) branch. After your confirmation and some additional tests, I'll merge it with master
