### ISSUE TITLE
there is issue with the commit: "change-relative-path-to-absolute helper"

### ISSUE THREAD

**Issue by judezhu** [oraclesorg/oracles-combine-solidity#20]
After i reverted the change, the lib works. 
It stops when try to find  "../math/SafeMath.sol".

Error message is:

!!!zeppelin-solidity/contracts/crowdsale/Crowdsale.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###zeppelin-solidity/contracts/crowdsale/Crowdsale.sol SOURCE FILE FOUND###
!!!zeppelin-solidity/contracts/token/MintableToken.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###zeppelin-solidity/contracts/token/MintableToken.sol SOURCE FILE FOUND###
###./Token.sol SOURCE FILE FOUND###
!!!../math/SafeMath.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!

**Comment by vbaranov** [comment]
@judezhu for which solidity project you are trying to create flat solidity file?

**Comment by vbaranov** [comment]
@judezhu thanks, I reproduced and fixed the mistake.
