### ISSUE TITLE
Wrong order again

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-combine-solidity#4]
Still doesn't work:

https://github.com/rstormsf/ico_per_week/blob/002_whitelisted/contracts/BlockchainLabsCrowdsale.sol

try to look at:
https://github.com/BlockCatIO/solidity-flattener

**Comment by vbaranov** [comment]
@rstormsf , thnx for contract example. Bug was found. We fixed it.
Let us, please, know, if the issue is solved for you.

**Comment by rstormsf** [comment]
@vbaranov looks good to me. I can consider the issue resolved
