### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-combine-solidity#8]
@vbaranov 
https://github.com/AigangNetwork/aigang-crowdsale-contracts/blob/master/contracts/PreSale.sol - try to `npm start` it

**Comment by vbaranov** [comment]
@rstormsf, I've checked. I can't confirm, that the problem exists:
```
oracles-combine-solidity-myfork viktor$ npm start ./aigang-crowdsale-contracts/contracts/PreSale.sol 

###./SafeMath.sol SOURCE FILE FOUND###
###./ERC20.sol SOURCE FILE FOUND###
###./MiniMeToken.sol SOURCE FILE FOUND###
###././ERC20.sol SOURCE FILE FOUND###
Success! Flat file is generated to ./out directory
```
And utility generates valid flat solidity file:
[PreSale_flat.txt](https://github.com/oraclesorg/oracles-combine-solidity/files/1302472/PreSale_flat.txt)

Are you still faced with this issue?

**Comment by rstormsf** [comment]
I just doubled checked it and I was at https://github.com/oraclesorg/oracles-combine-solidity/commit/c3260b29fb1050cac98a13bb2f3e5ab57cb8d545 commit. Did git pull and ran `npm start` again - it seems to be working fine.
