### ISSUE TITLE
Not combining all scripts at windows

### ISSUE THREAD

**Issue by tadejoremuz** [oraclesorg/oracles-combine-solidity#9]
Hi, 
i tested oracles-combine-solidity with my smart contracts and smart contracts that were published on github for educational purposes - and used in youtube tutorial (https://www.youtube.com/watch?v=ShW2zQcY4LY) . 

Issue is that when i run npm start path_to_sol_file i get this otuput: 

 oracles-combine-solidity@1.0.0 start C:\oracles-combine-solidity
> node index.js "C:\emx\contracts\emxCrowdSale.sol"

!!!zeppelin-solidity/contracts/crowdsale/Crowdsale.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###zeppelin-solidity/contracts/crowdsale/Crowdsale.sol SOURCE FILE FOUND###
!!!zeppelin-solidity/contracts/token/MintableToken.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###zeppelin-solidity/contracts/token/MintableToken.sol SOURCE FILE FOUND###
###./emrToken.sol SOURCE FILE FOUND###
!!!zeppelin-solidity/contracts/token/MintableToken.sol SOURCE FILE NOT FOUND. TRY TO FIND IT RECURSIVELY!!!
###zeppelin-solidity/contracts/token/MintableToken.sol SOURCE FILE FOUND###
Success! Flat file is generated to ./out directory

but in output file there are only functions/contracts that i created (or the ones from test project that i mentioned above) and not any other like MintableToken etc. What could i do? 

My npm details: 

npm version
{ 'oracles-combine-solidity': '1.0.0',
  npm: '5.4.2',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.5.0',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.14.1',
  v8: '6.0.287.53',
  zlib: '1.2.11' }

best regards, 
Tadej

**Comment by vbaranov** [comment]
Hi @tadejoremuz 
Are zeppelin-solidity contracts present in your project folder? They should be there too.
I don't see `zeppelin-solidity` npm package.
Try to install it `npm install zeppelin-solidity --save`
And after that try to combine solidity to flat file with the same command, you used before.
The flat source file should appear in ./out directory.

**Comment by tadejoremuz** [comment]
Hi, 
my contracts are in: 

C:\emx\contracts
and zeppelin-solidity located in: c:\emx\node_modules\zeppelin-solidity 

I also just tried to run  npm install zeppelin-solidity --save  and combine solidity with:  npm start C:\emx\contracts\emxCrowdSale.sol but still same result. 


best regards, 
Tadej

**Comment by vbaranov** [comment]
It seems, that project's structure is correct.
Did you try to compile the combined flat file with [Remix](http://remix.ethereum.org/)? Is it failed?
Maybe, you have this solidity project publicly in github, we'll be able to make tests on it in this case.

**Comment by tadejoremuz** [comment]
combined flat file compiles with remix only if i add
 import 'github.com/OpenZeppelin/zeppelin-solidity/contracts/crowdsale/Crowdsale.sol';
import 'github.com/OpenZeppelin/zeppelin-solidity/contracts/token/MintableToken.sol';

Otherwise returns: Declaration error: Identifier not found for MintableToken 


I tried to download this project too, and same result as in mine: 
https://github.com/rstormsf/ico_per_week/tree/001_crowdsale   


best regards, 
Tadej

**Comment by vbaranov** [comment]
I've just checked for all contracts from the link, you mentioned. It works.
Do you use the last version of oracles-combine-solidity?

The steps of my testing:
```
1. git clone https://github.com/rstormsf/ico_per_week -b 001_crowdsale
2. cd ico_per_week
3. npm install
4. cd ../oracles-combine-solidity-myfork/
5. npm start ./ico_per_week-001_crowdsale/contracts/BlockchainLabsCrowdsale.sol
```
Do you use the same scenario?

**Comment by vbaranov** [comment]
@tadejoremuz is your issue solved?

**Comment by tadejoremuz** [comment]
Hi, 
issue on windows is still there, so i'm using my linux os for combine-solidity as i was unable to sole issue on windows machine. 

best regards, 
Tadej

**Comment by oceanapplications** [comment]
I'm also having the same issue on windows.
